title: CLEF 2025 SimpleText
email: contact@simpletext-project.com
description: >- # this means to ignore newlines until "baseurl:"
        SimpleText is a track organised as a part of <a href="https://clef2025.clef-initiative.eu/">CLEF 2025 conference</a>, 
        initiated by <a href="http://www.clef-initiative.eu/">CLEF initiative</a>.
url: "http://simpletext-project.com/2025/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SimpletextW
github_username:  simpletext-madics

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
